[package]
name = "personal_library_cli"
version = "0.1.0"
authors = ["corsen-olbin <corbinolsen97@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
